-- Keyword status migration for H2 (safe to re-run)
-- Goals:
-- 1) Ensure STATUS column exists
-- 2) Backfill STATUS from ENABLED values
-- 3) Enforce STATUS NOT NULL
-- 4) Remove legacy ENABLED column

ALTER TABLE KEYWORD ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20);

-- Ensure backfill SQL is safe even when ENABLED was already removed
ALTER TABLE KEYWORD ADD COLUMN IF NOT EXISTS ENABLED BOOLEAN;

UPDATE KEYWORD
SET STATUS = CASE
    WHEN ENABLED IS FALSE THEN 'PAUSED'
    ELSE 'ACTIVE'
END
WHERE STATUS IS NULL;

ALTER TABLE KEYWORD ALTER COLUMN STATUS SET NOT NULL;
ALTER TABLE KEYWORD DROP COLUMN IF EXISTS ENABLED;
