-- 기본 키워드 시딩 (중복 방지: MERGE 사용)
MERGE INTO KEYWORD (NAME, ENABLED, CREATED_AT) KEY(NAME) VALUES ('AI', true, CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, ENABLED, CREATED_AT) KEY(NAME) VALUES ('LLM', true, CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, ENABLED, CREATED_AT) KEY(NAME) VALUES ('Open Ai', true, CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, ENABLED, CREATED_AT) KEY(NAME) VALUES ('Google', true, CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, ENABLED, CREATED_AT) KEY(NAME) VALUES ('사이버보안', true, CURRENT_TIMESTAMP);