-- Default keyword seed data (idempotent by KEY(NAME))
MERGE INTO KEYWORD (NAME, STATUS, CREATED_AT) KEY(NAME) VALUES ('ai', 'ACTIVE', CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, STATUS, CREATED_AT) KEY(NAME) VALUES ('llm', 'ACTIVE', CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, STATUS, CREATED_AT) KEY(NAME) VALUES ('open ai', 'ACTIVE', CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, STATUS, CREATED_AT) KEY(NAME) VALUES ('google', 'ACTIVE', CURRENT_TIMESTAMP);
MERGE INTO KEYWORD (NAME, STATUS, CREATED_AT) KEY(NAME) VALUES ('사이버보안', 'ACTIVE', CURRENT_TIMESTAMP);
